http:
  routers:
#    http-catchall:
#      rule: "HostRegexp(`{host:.+}`)"
#      priority: 1000
#      entryPoints:
#        - web
#      middlewares:
#        - redirect-to-https
#      service: api@internal
    api:
      entryPoints:
        - web
        - websecure
      rule: Host(`{{env "TRAEFIK_HOSTNAME"}}`)
      service: api@internal
#      middlewares:
#        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$aqhtg1ec$Ky6Dn7.hv46gMF0KvxoGu1"
    redirect-to-https:
      redirectScheme:
        scheme: https

    my-souin:
      plugin:
        souin:
          default_cache:
            headers: Authorization,Content-Type
            regex:
              exclude: ARegexHere
            ttl: 10s
          log_level: debug
          urls:
            domain.com/testing:
              headers: Authorization
              ttl: 2s
            mysubdomain.domain.com:
              headers: Authorization,Content-Type
              ttl: 50s
          ykeys:
            The_First_Test:
              headers:
                Content-Type: .+
            The_Second_Test:
              url: the/second/.+
